name: release-nozl-build
on:
  push:
    branches:
      - nozl-dev
      - main
      - feature/sc-2919/update-nats-server-s-dockerfile-and-github

jobs:
  release-artifact:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          workdir: "${{ inputs.workdir }}"
          version: latest
          args: release --snapshot --config .goreleaser-nightly.yml

      - name: Authenticate with GCP
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "${{ secrets.GCP_WORLDLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SA_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          access_token_lifetime: 300s

      - name: Login into Google Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev/nozl-default/nozl-dev-docker-22b822f6
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Tag Docker image and push to Google Artifact Registry
        shell: bash
        run: |
          docker tag nozl-api:${{ steps.vars.outputs.short_sha }} europe-west3-docker.pkg.dev/nozl-default/nozl-dev-docker-22b822f6/nozl-api:latest
          docker tag nozl-api:${{ steps.vars.outputs.short_sha }} europe-west3-docker.pkg.dev/nozl-default/nozl-dev-docker-22b822f6/nozl-api:${{ steps.vars.outputs.short_sha }}

          docker push europe-west3-docker.pkg.dev/nozl-default/nozl-dev-docker-22b822f6/nozl-api:${{ steps.vars.outputs.short_sha }}
          docker push europe-west3-docker.pkg.dev/nozl-default/nozl-dev-docker-22b822f6/nozl-api:latest
